version: "3.8"
services:
    app:
        build:
            args:
                user: user
                uid: 1000
            context: ./
            dockerfile: ./dockerfiles/app/Dockerfile
        image: sineverba/resumecv-backend-app:0.2.0
        container_name: resumecv-backend-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - resumecv-backend

    nginx:
        image: nginx:1.23.3-alpine-slim
        container_name: resumecv-backend-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./dockerfiles/nginx:/etc/nginx/conf.d/
        networks:
            - resumecv-backend

networks:
    resumecv-backend:
        name: resumecv-backend
        driver: bridge
