version: "3.8"
services:
    app:
        build:
            args:
                user: user
                uid: 1000
            context: ./
            dockerfile: dockerfiles/development/docker/Dockerfile
        image: sineverba/resumecv-backend-app:1.3.0-dev
        container_name: resumecv-backend-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - resumecv-backend

    nginx:
        image: nginx:1.25.3-alpine3.18-slim
        container_name: resumecv-backend-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./dockerfiles/development/nginx:/etc/nginx/conf.d/
        networks:
            - resumecv-backend
    db:
        image: mysql:8.2.0
        container_name: resumecv-backend-mysql
        environment:
            MYSQL_DATABASE: resumecv
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_USER: user
        ports:
            - "3306:3306"
        volumes:
            - ./dockerfiles/development/mysql:/docker-entrypoint-initdb.d
        networks:
            - resumecv-backend

    adminer:
            image: adminer:4.8.1-standalone
            container_name: resumecv-backend-adminer
            ports:
                - "7000:8080"
            networks:
                - resumecv-backend

networks:
    resumecv-backend:
        name: resumecv-backend
        driver: bridge
