version: 2.1
orbs:
  qodana: jetbrains/qodana@2022.3.2
jobs:
  scan:
    machine:
      image: 'ubuntu-2004:2022.10.1'
    steps:
      - checkout
      - qodana/scan
  test-unit:
    docker:
      - image: sineverba/php8xc:1.13.0
    steps:
      - checkout
      - run: composer install
      - run: cp .env.example .env
      - run: php artisan key:generate
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  tests:
    jobs:
      - scan:
          context: qodana
      - test-unit:
          filters:
            branches:
              only:
                - master
                - develop
