version: "3.8"
services:
    resumecv-backend:
        image: registry.gitlab.com/cicdprojects/resumecv-backend:0.7.0
        container_name: ${CONTAINER_NAME}
        restart: unless-stopped
        env_file:
            - ./.env
        networks:
            - proxy
            - manage
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.${CONTAINER_NAME}.entrypoints=websecure"
            - "traefik.http.routers.${CONTAINER_NAME}.service=${CONTAINER_NAME}"
            - "traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${HOST}`)"
            - "traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=${PORT}"

networks:
    proxy:
        external: true
    manage:
        name: manage
        driver: bridge
