version: v1.0

name: Build
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004

global_job_config:
  secrets:
    - name: ACCESS_TOKENS
  env_vars:
    - name: DOCKER_IMAGE
      value: registry.gitlab.com/cicdprojects/resumecv-backend
    - name: GITLAB_REGISTRY
      value: registry.gitlab.com
    - name: BUILDX_VERSION
      value: 0.10.0
    - name: BINFMT_VERSION
      value: qemu-v7.0.0-28
    - name: FOLDER_APP
      value: resumecv-backend

blocks:
  - name: "Build"
    task:
      jobs:
        - name: Create docker image
          commands:
            - checkout
            - docker login -u semaphore -p $GITLAB_TOKEN $GITLAB_REGISTRY
            - mkdir -vp ~/.docker/cli-plugins/
            - >-
              curl
              --silent
              -L "https://github.com/docker/buildx/releases/download/v$BUILDX_VERSION/buildx-v$BUILDX_VERSION.linux-amd64"
              > ~/.docker/cli-plugins/docker-buildx
            - chmod a+x ~/.docker/cli-plugins/docker-buildx
            - docker buildx version
            - docker run --rm --privileged tonistiigi/binfmt:$BINFMT_VERSION --install all
            - docker buildx ls
            - docker buildx create --name multiarch --driver docker-container --use
            - docker buildx inspect --bootstrap --builder multiarch
            - >-
              docker buildx build
              --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
              --tag $DOCKER_IMAGE:$SEMAPHORE_GIT_TAG_NAME
              --tag $DOCKER_IMAGE:latest
              --push
              --file dockerfiles/production/build/docker/Dockerfile "."

promotions:
  - name: Deploy
    pipeline_file: deploy.yml
    auto_promote:
      when: "result = 'passed' and tag =~ '.*'"
