version: v1.0

name: Build and deploy
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004

global_job_config:
  secrets:
    - name: ACCESS_TOKENS
    - name: VPS

  env_vars:
    - name: GITLAB_REGISTRY
      value: registry.gitlab.com
    - name: GITLAB_IMAGE_NAME
      value: resumecv-backend

blocks:
  - name: "Build and deploy image"
    dependencies: []
    task:
      jobs:
        - name: Build and push to Gitlab
          commands:
            - checkout
            - docker login -u semaphore -p $GITLAB_TOKEN $GITLAB_REGISTRY
            - docker build --tag $GITLAB_REGISTRY/cicdprojects/$GITLAB_IMAGE_NAME:latest --file dockerfiles/app/Dockerfile.production "."
            - docker push $GITLAB_REGISTRY/cicdprojects/$GITLAB_IMAGE_NAME:latest
  - name: "Deploy to VPS"
    dependencies: ["Build and deploy image"]
    task:
      jobs:
        - name: Deploy to VPS
          commands:
            - ssh-keyscan -p $VPS_GCP_PORT -H $VPS_GCP_URL >> ~/.ssh/known_hosts
            - chmod 0600 ~/.ssh/id_rsa_semaphoreci
            - ssh-add ~/.ssh/id_rsa_semaphoreci
            - ssh -t $VPS_GCP_USERNAME@$VPS_GCP_URL -p $VPS_GCP_PORT "cd $GITLAB_IMAGE_NAME && docker-compose stop && exit"
            - ssh -t $VPS_GCP_USERNAME@$VPS_GCP_URL -p $VPS_GCP_PORT "docker container rm $GITLAB_IMAGE_NAME && docker image rm $GITLAB_REGISTRY/cicdprojects/$GITLAB_IMAGE_NAME:latest && exit"
            - ssh -t $VPS_GCP_USERNAME@$VPS_GCP_URL -p $VPS_GCP_PORT "docker pull $GITLAB_REGISTRY/cicdprojects/$GITLAB_IMAGE_NAME:latest && exit"
            #- ssh -t $VPS_GCP_USERNAME@$VPS_GCP_URL -p $VPS_GCP_PORT "sed -i \"/APP_VERSION=/c\APP_VERSION=$SEMAPHORE_GIT_TAG_NAME\" $GITLAB_IMAGE_NAME/.env && exit"
            - ssh -t $VPS_GCP_USERNAME@$VPS_GCP_URL -p $VPS_GCP_PORT "cd $GITLAB_IMAGE_NAME && docker-compose up -d && exit"
